---

- name: Sync package database
  become: true
  become_user: root
  apt:
    update_cache: yes

- name: Install common packages
  become: true
  become_user: root
  apt:
    name: "{{ pkgs_common }}"
    state: present

- name: Install ubuntu packages
  become: true
  become_user: root
  apt:
    name: "{{ pkgs_ubuntu }}"
    state: present

...
