---

- name: Enable nonfree repo
  become: true
  become_user: root
  xbps:
    name: void-repo-nonfree
    state: present

- name: Enable multilib repo
  become: true
  become_user: root
  xbps:
    name: void-repo-multilib
    state: present

- name: Sync package database
  become: true
  become_user: root
  xbps:
    update_cache: yes

- name: Install common packages
  become: true
  become_user: root
  xbps:
    name: "{{ pkgs_common }}"
    state: present

- name: Install void packages
  become: true
  become_user: root
  xbps:
    name: "{{ pkgs_void }}"
    state: present

...
