---

- name: Run void tasks
  import_tasks: os/void.yml
  when: ansible_distribution == "Void" or ansible_distribution == "void"

- name: Run debian tasks
  import_tasks: os/debian.yml
  when: ansible_distribution == "Debian"

- name: Set default user shell
  become: true
  become_user: root
  user:
    name: "{{ item }}"
    shell: /bin/bash
  loop:
    - "{{ ansible_env.USER }}"
    - root

# TODO: add user to sudoers file

...
