---

- name: Run void tasks
  import_tasks: os/void.yml
  when: ansible_distribution == "Void" or ansible_distribution == "void"

- name: Run debian tasks
  import_tasks: os/debian.yml
  when: ansible_distribution == "Debian"

- name: Deploy tmux config
  file:
    src: "{{ dotfiles_path }}/tmux/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link

- name: Deploy neovim config
  file:
    src: "{{ dotfiles_path }}/nvim/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/nvim/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
  loop:
    - init.vim
    - colors/zenburn.vim

- name: Deploy i3 config
  file:
    src: "{{ dotfiles_path }}/i3/config"
    dest: "{{ ansible_env.HOME }}/.config/i3/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link

- name: Deploy i3blocks config
  become: true
  become_user: root
  file:
    src: "{{ dotfiles_path }}/i3/i3blocks/i3blocks.conf"
    dest: "/etc/i3blocks.conf"
    state: link
    force: yes

- name: Deploy newsboat config
  file:
    src: "{{ dotfiles_path }}/newsboat/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.newsboat/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
  loop:
    - config
    - urls

- name: Deploy ranger config
  file:
    src: "{{ dotfiles_path }}/ranger/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/ranger/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
  loop:
    - commands.py
    - rc.conf

- name: Deploy qutebrowser config
  file:
    src: "{{ dotfiles_path }}/qutebrowser/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/qutebrowser/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
    force: yes
  loop:
    - config.py
    - quickmarks
    - bookmarks/urls

- name: Deploy rofi config
  file:
    src: "{{ dotfiles_path }}/rofi/config.rasi"
    dest: "{{ ansible_env.HOME }}/.config/rofi/config.rasi"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link

- name: Deploy urxvt config
  file:
    src: "{{ dotfiles_path }}/urxvt/.Xresources"
    dest: "{{ ansible_env.HOME }}/.Xresources"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link

- name: Deploy xfce4-terminal config
  file:
    src: "{{ dotfiles_path }}/xfce4_terminal/terminalrc"
    dest: "{{ ansible_env.HOME }}/.config/xfce4/terminal/terminalrc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
    force: yes

- name: Deploy nitrogen config
  file:
    src: "{{ dotfiles_path }}/nitrogen/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/nitrogen/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
  loop:
    - bg-saved.cfg
    - nitrogen.cfg

- name: Deploy bash config
  file:
    src: "{{ dotfiles_path }}/bash/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
    force: yes
  loop:
    - .bash_aliases
    - .bashrc

- name: Deploy .env config
  file:
    src: "{{ dotfiles_path }}/system/.env"
    dest: "{{ ansible_env.HOME }}/.env"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link

- name: Deploy .profile config
  file:
    src: "{{ dotfiles_path }}/system/.profile"
    dest: "{{ ansible_env.HOME }}/.profile"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
    force: yes

- name: Deploy zathura config
  file:
    src: "{{ dotfiles_path }}/zathura/zathurarc"
    dest: "{{ ansible_env.HOME }}/.config/zathura/zathurarc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
    mode: '755'

# TODO: improve this by using symbolic link
- name: Deploy lightdm config
  become: true
  become_user: root
  copy:
    remote_src: yes
    src: "{{ dotfiles_path }}/lightdm/lightdm-gtk-greeter.conf"
    dest: "/etc/lightdm/lightdm-gtk-greeter.conf"
    owner: root
    group: root
    force: yes

- name: Deploy resources
  file:
    src: "{{ dotfiles_path }}/resources/images/{{ item }}"
    dest: "{{ ansible_env.HOME }}/images/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
  loop:
    - bg.png
    - avatar.jpg
    - wallpaper.jpg

- name: Deploy lightdm resources
  become: true
  become_user: root
  copy:
    remote_src: yes
    src: "{{ dotfiles_path }}/resources/images/avatar.jpg"
    dest: "/opt/lightdm/resources/avatar.jpg" # TODO: change this directory
    owner: root
    group: root

- name: Deploy tmuxp files
  file:
    src: "{{ dotfiles_path }}/tmux/.tmuxp/"
    dest: "{{ ansible_env.HOME }}/.tmuxp"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link

- name: Deploy scripts
  file:
    src: "{{ dotfiles_path }}/scripts"
    dest: "{{ ansible_env.HOME }}/.scripts"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
    mode: '755'

- name: Deploy i3blocks scripts
  file:
    src: "{{ dotfiles_path }}/i3/i3blocks/scripts"
    dest: "{{ ansible_env.HOME }}/.scripts/i3blocks"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
    mode: '755'

- name: Deploy betterlockscreen config
  file:
    src: "{{ dotfiles_path }}/betterlockscreen"
    dest: "{{ ansible_env.HOME }}/.cache/betterlockscreen"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
    mode: '755'

- name: Deploy volumeicon config
  file:
    src: "{{ dotfiles_path }}/volumeicon/volumeicon"
    dest: "{{ ansible_env.HOME }}/.config/volumeicon/volumeicon"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
    mode: '755'
    force: yes

...
