---

- name: Clone configs repo
  git:
    repo: "https://github.com/andrelcmoreira/configs.git"
    dest: "{{ ansible_env.HOME }}/dev/projects/configs"
    version: debian
    force: yes

- name: Deploy .xsession config
  file:
    src: "{{ dotfiles_path }}/system/.xsession"
    dest: "{{ ansible_env.HOME }}/.xsession"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
    force: yes

...
