---

- name: Clone configs repo
  git:
    repo: "https://github.com/andrelcmoreira/configs.git"
    dest: "{{ ansible_env.HOME }}/dev/projects/configs"
    version: void
    force: yes

- name: Deploy .profile config
  file:
    src: "{{ dotfiles_path }}/system/.profile"
    dest: "{{ ansible_env.HOME }}/.profile"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
    force: yes

...
