---

- name: Run void tasks
  import_tasks: os/void.yml
  when: ansible_distribution == "Void" or ansible_distribution == "void"

- name: Run ubuntu tasks
  import_tasks: os/ubuntu.yml
  when: ansible_distribution == "Ubuntu"

...
