---

- name: Install vim-plug
  shell: curl -fLo \
           "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim \
           --create-dirs \
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Install neovim plugins
  shell: nvim -c 'PlugInstall | q | q'

- name: Install coc plugins
  shell: nvim -c 'CocInstall -sync {{ item }} | q | q'
  loop:
    - coc-clangd
    - coc-jedi
    - coc-rust-analyzer
    - "@yaegassy/coc-mypy"

...
