---

- name: Creating dev directory
  file:
    path: "{{ ansible_env.HOME }}/dev"
    state: directory
    mode: '0755'

- name: Creating docs directory
  file:
    path: "{{ ansible_env.HOME }}/docs"
    state: directory
    mode: '0755'

- name: Creating downloads directory
  file:
    path: "{{ ansible_env.HOME }}/downloads"
    state: directory
    mode: '0755'

- name: Creating images directory
  file:
    path: "{{ ansible_env.HOME }}/images"
    state: directory
    mode: '0755'

- name: Creating musics directory
  file:
    path: "{{ ansible_env.HOME }}/musics"
    state: directory
    mode: '0755'

- name: Creating videos directory
  file:
    path: "{{ ansible_env.HOME }}/videos"
    state: directory
    mode: '0755'

- name: Creating projects directory
  file:
    path: "{{ ansible_env.HOME }}/dev/projects/"
    state: directory
    mode: '0755'

- name: Creating .config directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0700'

- name: Creating i3 config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/i3"
    state: directory
    mode: '0755'

- name: Creating neovim config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - nvim
    - nvim/colors

- name: Creating qutebrowser config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/qutebrowser"
    state: directory
    mode: '0700'

- name: Creating ranger config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/ranger"
    state: directory
    mode: '0755'

- name: Creating rofi config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/rofi"
    state: directory
    mode: '0755'

- name: Creating nitrogen config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/nitrogen"
    state: directory
    mode: '0755'

- name: Creating newsboat config directory
  file:
    path: "{{ ansible_env.HOME }}/.newsboat"
    state: directory
    mode: '0755'

- name: Creating xfce4-terminal config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/xfce4/terminal"
    state: directory
    mode: '0755'

- name: Creating zathura config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/zathura"
    state: directory
    mode: '0755'

- name: Creating volumeicon config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/volumeicon"
    state: directory
    mode: '0755'

- name: Creating lightdm resources directory
  become: true
  become_user: root
  file:
    path: "/opt/lightdm/resources"
    state: directory
    mode: '0755'

- name: Creating .cache directory
  file:
    path: "{{ ansible_env.HOME }}/.cache"
    state: directory
    mode: '0755'

...
