---

- name: Add user to groups
  become: true
  become_user: root
  shell: usermod -aG {{ item }} {{ ansible_env.USER }}
  loop:
    - audio
    - docker
    - network

- name: Set default user shell
  become: true
  become_user: root
  user:
    name: "{{ item }}"
    shell: /bin/bash
    loop:
      - "{{ ansible_env.USER }}"
      - root

# TODO: add user to sudoers file

...
