---

- name: Sync package database
  become: true
  become_user: root
  xbps:
    update_cache: yes

# TODO: put the packages into a global variable
- name: Install common packages
  become: true
  become_user: root
  xbps:
    name: "{{ pkgs }}"
    state: present
  vars:
    pkgs:
      - bash
      - ctags
      - curl
      - docker
      - docker-compose
      - evince
      - firefox
      - fzf
      - gimp
      - git
      - htop
      - i3blocks
      - lightdm
      - lightdm-gtk3-greeter
      - mpv
      - neofetch
      - qutebrowser
      - ranger
      - rxvt-unicode
      - rofi
      - shellcheck
      - strace
      - tmux
      - vim
      - wget
      - zathura

- name: Install void packages
  become: true
  become_user: root
  xbps:
    name: "{{ pkgs }}"
    state: present
  vars:
    pkgs:
      - acpi
      - adwaita-qt
      - adwaita-plus
      - alsa-utils
      - base-devel
      - betterlockscreen
      - font-awesome
      - gtk-theme-united-gnome
      - i3-gaps
      - man-pages-devel
      - man-pages-posix
      - neovim
      - network-manager-applet
      - newsboat
      - nitrogen
      - python3-pip
      - python3-tmuxp
      - python3-neovim
      - recordmydesktop
      - scrot
      - setxkbmap
      - telegram-desktop
      - texlive2020-bin
      - the_silver_searcher
#      - unrar
      - urxvt-perls
      - volumeicon
      - xbacklight
      - xclipboard
      - xfce4-terminal
      - xorg-fonts
      - xorg-minimal
      - w3m-img
      - zathura-pdf-mupdf

- name: Install vim-plug
  shell: curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim \
         --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#- name: Install neovim plugins
#  shell: nvim -c 'PluginInstall | q | q'

# TODO: coc stuff
# TODO: git configs
...
