---

- name: Run void tasks
  import_tasks: os/void.yml
  when: ansible_distribution == "Void" or ansible_distribution == "void"

- name: Run debian tasks
  import_tasks: os/debian.yml
  when: ansible_distribution == "Debian"

- name: Install rust packages
  shell: rustup-init -y -c "{{ pkgs_rust }}"

...
