---

- name: Creating dev directory
  file:
    path: "{{ global.home_dir }}/dev"
    state: directory
    mode: '0755'

- name: Creating docs directory
  file:
    path: "{{ global.home_dir }}/docs"
    state: directory
    mode: '0755'

- name: Creating downloads directory
  file:
    path: "{{ global.home_dir }}/downloads"
    state: directory
    mode: '0755'

- name: Creating images directory
  file:
    path: "{{ global.home_dir }}/images"
    state: directory
    mode: '0755'

- name: Creating musics directory
  file:
    path: "{{ global.home_dir }}/musics"
    state: directory
    mode: '0755'

- name: Creating videos directory
  file:
    path: "{{ global.home_dir }}/videos"
    state: directory
    mode: '0755'

- name: Creating projects directory
  file:
    path: "{{ global.home_dir }}/dev/projects/"
    state: directory
    mode: '0755'

- name: Creating .config directory
  file:
    path: "{{ global.home_dir }}/.config"
    state: directory
    mode: '0700'

- name: Creating i3 config directory
  file:
    path: "{{ global.home_dir }}/.config/i3"
    state: directory
    mode: '0755'

- name: Creating neovim config directory
  file:
    path: "{{ global.home_dir }}/.config/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - nvim
    - nvim/colors

- name: Creating qutebrowser config directory
  file:
    path: "{{ global.home_dir }}/.config/qutebrowser"
    state: directory
    mode: '0700'

- name: Creating ranger config directory
  file:
    path: "{{ global.home_dir }}/.config/ranger"
    state: directory
    mode: '0755'

- name: Creating rofi config directory
  file:
    path: "{{ global.home_dir }}/.config/rofi"
    state: directory
    mode: '0755'

- name: Creating nitrogen config directory
  file:
    path: "{{ global.home_dir }}/.config/nitrogen"
    state: directory
    mode: '0755'

- name: Creating newsboat config directory
  file:
    path: "{{ global.home_dir }}/.newsboat"
    state: directory
    mode: '0755'

- name: Creating xfce4-terminal config directory
  file:
    path: "{{ global.home_dir }}/.config/xfce4/terminal"
    state: directory
    mode: '0755'

- name: Creating zathura config directory
  file:
    path: "{{ global.home_dir }}/.config/zathura"
    state: directory
    mode: '0755'

- name: Creating lightdm resources directory
  become: true
  become_user: root
  file:
    path: "/opt/lightdm/resources"
    state: directory
    mode: '0755'

...
