name: ci

on:
  push:
    branches:
      - main

jobs:
  yaml_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yaml coherence check
        run: ansible-playbook provision_host.yml --syntax-check
